# Generated by Django 2.2.5 on 2019-09-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=50)),
                ('paper_1', models.PositiveSmallIntegerField()),
                ('paper_2', models.PositiveSmallIntegerField()),
                ('paper_3', models.PositiveSmallIntegerField()),
                ('paper_4', models.PositiveSmallIntegerField()),
                ('paper_5', models.PositiveSmallIntegerField()),
                ('paper_6', models.PositiveSmallIntegerField()),
                ('paper_7', models.PositiveSmallIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.PositiveSmallIntegerField()),
                ('department_id', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
    ]
