# Generated by Django 2.2.7 on 2019-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('semester_name', models.CharField(max_length=50)),
                ('paper_1', models.PositiveSmallIntegerField()),
                ('paper_2', models.PositiveSmallIntegerField()),
                ('paper_3', models.PositiveSmallIntegerField()),
                ('paper_4', models.PositiveSmallIntegerField()),
                ('paper_5', models.PositiveSmallIntegerField()),
                ('paper_6', models.PositiveSmallIntegerField()),
                ('paper_7', models.PositiveSmallIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.PositiveSmallIntegerField()),
                ('department_id', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
